/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.period;

import controller.ControllerConfig;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import view.helper.HelperOfForms;

/**
 *
 * @author winvm
 */
public class FormConfig extends javax.swing.JDialog {

    /**
     * Creates new form FormConfig
     */
    public FormConfig(java.awt.Frame parent, boolean modal, ControllerConfig controller, int id) {
        super(parent, modal);
        initComponents();
        controllerConfig = controller;
        idPeriod = id;
        controllerConfig.getAllCriteria(this);
        controllerConfig.getAllSubCriteria(this);
        controllerConfig.getAllProcess(this);
        setLocationRelativeTo(null);
        enabledSubCriteria(false);
        enabledProcess(false);
        enabledQuestion(false);
    }

    public int getIdPeriod() {
        return idPeriod;
    }

    public int getIdPeriodCriteria() {
        return idPeriodCriteria;
    }

    public void setIdPeriodCriteria(int idPeriodCriteria) {
        this.idPeriodCriteria = idPeriodCriteria;
    }

    public int getIdPCSubCriteria() {
        return idPCSubCriteria;
    }

    public void setIdPCSubCriteria(int idPCSubCriteria) {
        this.idPCSubCriteria = idPCSubCriteria;
    }

    public int getIdPCSProcess() {
        return idPCSProcess;
    }

    public void setIdPCSProcess(int idPCSProcess) {
        this.idPCSProcess = idPCSProcess;
    }

    public JComboBox getCbCriteria() {
        return cbCriteria;
    }

    public JComboBox getCbProcess() {
        return cbProcess;
    }

    public JComboBox getCbSubCriteria() {
        return cbSubCriteria;
    }

    public JTextArea getTxtQuestion() {
        return txtQuestion;
    }

    public JTextField getTxtAdjustment() {
        return txtAdjustment;
    }

    public JTextField getTxtPercentage() {
        return txtPercentage;
    }

    public JTextField getTxtPointEfqm() {
        return txtPointEfqm;
    }

    private void clearFields(String value) {
        switch (value) {
            case "all":
                clearCriteria();
                enabledCriteria(true);
                clearSubCriteria();
                enabledSubCriteria(false);
                clearProcess();
                enabledProcess(false);
                clearQuestion();
                enabledQuestion(false);
                break;
            case "process":
                clearProcess();
                enabledProcess(true);
                clearQuestion();
                enabledQuestion(false);
                break;
            case "subcriteria":
                clearSubCriteria();
                enabledSubCriteria(true);
                clearProcess();
                enabledProcess(false);
                clearQuestion();
                enabledQuestion(false);
                break;
        }
    }

    private void clearCriteria() {
        HelperOfForms.cleanJComboBox(cbCriteria, "Seleccionar un Criterio");
        controllerConfig.getAllCriteria(this);
        txtPointEfqm.setText("");
    }

    private void clearSubCriteria() {
        HelperOfForms.cleanJComboBox(cbSubCriteria, "Seleccionar un SubCriterio");
        controllerConfig.getAllSubCriteria(this);
        txtAdjustment.setText("");
        txtPercentage.setText("");
    }

    private void clearProcess() {
        HelperOfForms.cleanJComboBox(cbProcess, "Seleccionar un Proceso");
        controllerConfig.getAllProcess(this);
    }

    private void clearQuestion() {
        txtQuestion.setText("");
    }

    public void enabledCriteria(boolean value) {
        cbCriteria.setEnabled(value);
        txtPointEfqm.setEnabled(value);
        btnSaveConfCriteria.setEnabled(value);
    }

    public void enabledSubCriteria(boolean value) {
        cbSubCriteria.setEnabled(value);
        txtAdjustment.setEnabled(value);
        txtPercentage.setEnabled(value);
        btnSaveConfSubCriteria.setEnabled(value);
    }

    public void enabledProcess(boolean value) {
        cbProcess.setEnabled(value);
        btnSaveConfProcess.setEnabled(value);
    }

    public void enabledQuestion(boolean value) {
        txtQuestion.setEnabled(value);
        btnSaveConfQuestion.setEnabled(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        panelCriteria = new javax.swing.JPanel();
        btnAddCriteria = new javax.swing.JButton();
        cbCriteria = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSaveConfCriteria = new javax.swing.JButton();
        btnNewConfCriteria = new javax.swing.JButton();
        txtPointEfqm = new javax.swing.JTextField();
        pabelSubCriteria = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbSubCriteria = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAddSubCriteria = new javax.swing.JButton();
        btnSaveConfSubCriteria = new javax.swing.JButton();
        btnNewConfSC = new javax.swing.JButton();
        txtAdjustment = new javax.swing.JTextField();
        txtPercentage = new javax.swing.JTextField();
        panelProcess = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbProcess = new javax.swing.JComboBox();
        btnAddProcess = new javax.swing.JButton();
        btnSaveConfProcess = new javax.swing.JButton();
        btnNewConfProc = new javax.swing.JButton();
        panelQuestion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        btnSaveConfQuestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Periodo - Configuracion");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnNext.setText("Limpiar todos los campos");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        panelCriteria.setBorder(javax.swing.BorderFactory.createTitledBorder("Conf. Criterio"));

        btnAddCriteria.setText("Nuevo Criterio");
        btnAddCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCriteriaActionPerformed(evt);
            }
        });

        cbCriteria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecicone un Criterio" }));

        jLabel1.setText("Criterio:");

        jLabel4.setText("Puntos EFQM:");

        btnSaveConfCriteria.setText("Agregar");
        btnSaveConfCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveConfCriteriaActionPerformed(evt);
            }
        });

        btnNewConfCriteria.setText("Modificar");
        btnNewConfCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewConfCriteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCriteriaLayout = new javax.swing.GroupLayout(panelCriteria);
        panelCriteria.setLayout(panelCriteriaLayout);
        panelCriteriaLayout.setHorizontalGroup(
            panelCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCriteria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCriteriaLayout.createSequentialGroup()
                        .addGroup(panelCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPointEfqm, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCriteriaLayout.createSequentialGroup()
                                .addComponent(btnSaveConfCriteria)
                                .addGap(18, 18, 18)
                                .addComponent(btnNewConfCriteria)))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnAddCriteria)
                .addContainerGap())
        );
        panelCriteriaLayout.setVerticalGroup(
            panelCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCriteria))
                .addGap(18, 18, 18)
                .addGroup(panelCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPointEfqm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveConfCriteria)
                    .addComponent(btnNewConfCriteria))
                .addGap(24, 24, 24))
        );

        pabelSubCriteria.setBorder(javax.swing.BorderFactory.createTitledBorder("Conf. SubCriterio"));

        jLabel2.setText("SubCriterio:");

        cbSubCriteria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar un SubCriterio" }));

        jLabel5.setText("Ajuste:");

        jLabel6.setText("Proc.:");

        btnAddSubCriteria.setText("Nuevo Subcriterio");
        btnAddSubCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSubCriteriaActionPerformed(evt);
            }
        });

        btnSaveConfSubCriteria.setText("Agregar");
        btnSaveConfSubCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveConfSubCriteriaActionPerformed(evt);
            }
        });

        btnNewConfSC.setText("Modificar");
        btnNewConfSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewConfSCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pabelSubCriteriaLayout = new javax.swing.GroupLayout(pabelSubCriteria);
        pabelSubCriteria.setLayout(pabelSubCriteriaLayout);
        pabelSubCriteriaLayout.setHorizontalGroup(
            pabelSubCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pabelSubCriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pabelSubCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(pabelSubCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pabelSubCriteriaLayout.createSequentialGroup()
                        .addComponent(cbSubCriteria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddSubCriteria))
                    .addGroup(pabelSubCriteriaLayout.createSequentialGroup()
                        .addGroup(pabelSubCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pabelSubCriteriaLayout.createSequentialGroup()
                                .addComponent(btnSaveConfSubCriteria)
                                .addGap(18, 18, 18)
                                .addComponent(btnNewConfSC))
                            .addComponent(txtAdjustment, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pabelSubCriteriaLayout.setVerticalGroup(
            pabelSubCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pabelSubCriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pabelSubCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbSubCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSubCriteria))
                .addGap(18, 18, 18)
                .addGroup(pabelSubCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAdjustment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pabelSubCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pabelSubCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveConfSubCriteria)
                    .addComponent(btnNewConfSC))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        panelProcess.setBorder(javax.swing.BorderFactory.createTitledBorder("Conf. Proceso"));

        jLabel3.setText("Proceso:");

        cbProcess.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Proceso" }));

        btnAddProcess.setText("Nuevo Proceso");
        btnAddProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProcessActionPerformed(evt);
            }
        });

        btnSaveConfProcess.setText("Agregar");
        btnSaveConfProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveConfProcessActionPerformed(evt);
            }
        });

        btnNewConfProc.setText("Modificar");
        btnNewConfProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewConfProcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProcessLayout = new javax.swing.GroupLayout(panelProcess);
        panelProcess.setLayout(panelProcessLayout);
        panelProcessLayout.setHorizontalGroup(
            panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProcessLayout.createSequentialGroup()
                        .addComponent(btnSaveConfProcess)
                        .addGap(26, 26, 26)
                        .addComponent(btnNewConfProc))
                    .addGroup(panelProcessLayout.createSequentialGroup()
                        .addComponent(cbProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddProcess)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        panelProcessLayout.setVerticalGroup(
            panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProcess))
                .addGap(34, 34, 34)
                .addGroup(panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveConfProcess)
                    .addComponent(btnNewConfProc))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelQuestion.setBorder(javax.swing.BorderFactory.createTitledBorder("Config. Pregunta"));

        jLabel7.setText("Pregunta:");

        txtQuestion.setColumns(20);
        txtQuestion.setLineWrap(true);
        txtQuestion.setRows(5);
        jScrollPane1.setViewportView(txtQuestion);

        btnSaveConfQuestion.setText("Agregar");
        btnSaveConfQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveConfQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQuestionLayout = new javax.swing.GroupLayout(panelQuestion);
        panelQuestion.setLayout(panelQuestionLayout);
        panelQuestionLayout.setHorizontalGroup(
            panelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(panelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQuestionLayout.createSequentialGroup()
                        .addComponent(btnSaveConfQuestion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelQuestionLayout.setVerticalGroup(
            panelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQuestionLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveConfQuestion)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnNext)
                        .addGap(71, 71, 71)
                        .addComponent(btnClose))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pabelSubCriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pabelSubCriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panelProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClose)
                            .addComponent(btnNext)))
                    .addComponent(panelQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCriteriaActionPerformed
        try {
            String criteria = JOptionPane.showInputDialog(this, "Ingrese un Criterio");
            if (!criteria.isEmpty()) {
                controllerConfig.saveCriteria(criteria);
                HelperOfForms.cleanJComboBox(cbCriteria, "Seleccionar un Criterio");
                controllerConfig.getAllCriteria(this);
            } else {
                JOptionPane.showMessageDialog(this, "El campo no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAddCriteriaActionPerformed

    private void btnAddSubCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSubCriteriaActionPerformed
        try {
            String subCriteria = JOptionPane.showInputDialog(this, "Ingrese un SubCriterio");
            if (!subCriteria.isEmpty()) {
                controllerConfig.saveSubCriteria(subCriteria);
                HelperOfForms.cleanJComboBox(cbSubCriteria, "Seleccionar un SubCriterio");
                controllerConfig.getAllSubCriteria(this);
            } else {
                JOptionPane.showMessageDialog(this, "El campo no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAddSubCriteriaActionPerformed

    private void btnAddProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProcessActionPerformed
        try {
            String process = JOptionPane.showInputDialog(this, "Ingrese un Proceso");
            if (!process.isEmpty()) {
                controllerConfig.saveProcess(process);
                HelperOfForms.cleanJComboBox(cbProcess, "Seleccionar un Proceso");
                controllerConfig.getAllProcess(this);
            } else {
                JOptionPane.showMessageDialog(this, "El campo no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAddProcessActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        clearFields("all");
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSaveConfCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveConfCriteriaActionPerformed
        controllerConfig.saveConfigPeriodCriteria(this);
    }//GEN-LAST:event_btnSaveConfCriteriaActionPerformed

    private void btnSaveConfSubCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveConfSubCriteriaActionPerformed
        controllerConfig.saveConfigPCSubCriteria(this);
    }//GEN-LAST:event_btnSaveConfSubCriteriaActionPerformed

    private void btnSaveConfProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveConfProcessActionPerformed
        controllerConfig.saveConfigPCSProcess(this);
    }//GEN-LAST:event_btnSaveConfProcessActionPerformed

    private void btnSaveConfQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveConfQuestionActionPerformed
        controllerConfig.saveConfigPCSPQuestion(this);
    }//GEN-LAST:event_btnSaveConfQuestionActionPerformed

    private void btnNewConfProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewConfProcActionPerformed
        clearFields("process");
    }//GEN-LAST:event_btnNewConfProcActionPerformed

    private void btnNewConfSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewConfSCActionPerformed
        clearFields("subcriteria");
    }//GEN-LAST:event_btnNewConfSCActionPerformed

    private void btnNewConfCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewConfCriteriaActionPerformed
        clearFields("all");
    }//GEN-LAST:event_btnNewConfCriteriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCriteria;
    private javax.swing.JButton btnAddProcess;
    private javax.swing.JButton btnAddSubCriteria;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNewConfCriteria;
    private javax.swing.JButton btnNewConfProc;
    private javax.swing.JButton btnNewConfSC;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSaveConfCriteria;
    private javax.swing.JButton btnSaveConfProcess;
    private javax.swing.JButton btnSaveConfQuestion;
    private javax.swing.JButton btnSaveConfSubCriteria;
    private javax.swing.JComboBox cbCriteria;
    private javax.swing.JComboBox cbProcess;
    private javax.swing.JComboBox cbSubCriteria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pabelSubCriteria;
    private javax.swing.JPanel panelCriteria;
    private javax.swing.JPanel panelProcess;
    private javax.swing.JPanel panelQuestion;
    private javax.swing.JTextField txtAdjustment;
    private javax.swing.JTextField txtPercentage;
    private javax.swing.JTextField txtPointEfqm;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables
    private ControllerConfig controllerConfig;
    private int idPeriod;
    private int idPeriodCriteria;
    private int idPCSubCriteria;
    private int idPCSProcess;
}
