/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.criterias;

import controller.ControllerCriteria;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import view.helper.CustomTableModel;
import view.helper.HelperOfForms;

/**
 *
 * @author winvm
 */
public class ListCriteria extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListCriterias
     */
    public ListCriteria(JFrame parent) {
        this.parent = parent;
        String[] columns = {"ID", "Criterio"};
        table = new JTable();
        model = new CustomTableModel();
        HelperOfForms.initTable(table, model, columns);
        initComponents();
        controllerCriteria = new ControllerCriteria();
        controllerCriteria.getAllCriterias(this);
    }

    public CustomTableModel getModel() {
        return model;
    }

    public JTable getTable() {
        return table;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        addUpdate = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane(table);

        setClosable(true);
        setIconifiable(true);
        setTitle("Criterios");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAdd.setText("Nuevo");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);
        jToolBar1.add(jSeparator2);

        addUpdate.setText("Actualizar");
        addUpdate.setFocusable(false);
        addUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUpdateActionPerformed(evt);
            }
        });
        jToolBar1.add(addUpdate);
        jToolBar1.add(jSeparator3);

        btnDelete.setText("Eliminar");
        btnDelete.setEnabled(false);
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        FormCriteria form = new FormCriteria(parent, true, controllerCriteria);
        form.setVisible(true);
        HelperOfForms.cleanModel(model);
        controllerCriteria.getAllCriterias(this);
    }//GEN-LAST:event_btnAddActionPerformed

    private void addUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUpdateActionPerformed
        try {
            FormCriteria form = new FormCriteria(parent, true, controllerCriteria, HelperOfForms.getValueOfCell(table, model, 0));
            form.setVisible(true);
            HelperOfForms.cleanModel(model);
            controllerCriteria.getAllCriterias(this);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Criterio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(parent, "Desea elimiar el Criterio?", "Confirmacion", JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
                controllerCriteria.deleteCriteria(this, HelperOfForms.getValueOfCell(table, model, 0));
                HelperOfForms.cleanModel(model);
                controllerCriteria.getAllCriterias(this);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUpdate;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    private CustomTableModel model;
    private JTable table;
    private ControllerCriteria controllerCriteria;
    private JFrame parent;
}
