/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.questions;

import controller.ControllerQuestion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import view.helper.CustomTableModel;
import view.helper.HelperOfForms;

/**
 *
 * @author winvm
 */
public class ListQuestion extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListQuestions
     */
    public ListQuestion(JFrame parent) {
        try {
            this.parent = parent;
            table = new JTable();
            model = new CustomTableModel();
            String[] column = {"ID", "Pregunta"};
            HelperOfForms.initTable(table, model, column);
            initComponents();
            controller = new ControllerQuestion();
            controller.getAllQuestions(this);
        } catch (SQLException ex) {
            Logger.getLogger(ListQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public JTable getTable() {
        return table;
    }

    public CustomTableModel getModel() {
        return model;
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane(table);
        jToolBar1 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnUpdateQuestion = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Preguntas");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAdd.setText("Nueva");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);
        jToolBar1.add(jSeparator2);

        btnUpdateQuestion.setText("Actualizar");
        btnUpdateQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateQuestionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUpdateQuestion);
        jToolBar1.add(jSeparator3);

        btnDelete.setText("Eliminar");
        btnDelete.setEnabled(false);
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            FormQuestion formQuestion = new FormQuestion(parent, true, controller);
            formQuestion.setVisible(true);
            HelperOfForms.cleanModel(model);
            controller.getAllQuestions(this);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al recuperar las Preguntas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateQuestionActionPerformed
        try {
            FormQuestion formQuestion = new FormQuestion(parent, true, controller, HelperOfForms.getValueOfCell(table, model, 0));
            formQuestion.setVisible(true);
            HelperOfForms.cleanModel(model);
            controller.getAllQuestions(this);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateQuestionActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(parent, "Desea elimiar la pregunta?", "Confirmacion", JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
                controller.delete(this, HelperOfForms.getValueOfCell(table, model, 0));
                HelperOfForms.cleanModel(model);
                controller.getAllQuestions(this);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdateQuestion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    private JTable table;
    private CustomTableModel model;
    private ControllerQuestion controller;
    private JFrame parent;
}
